### ISSUE TITLE
Folder `templates/visa-base/http` missing?

### ISSUE THREAD

**Issue by Atlas974** [ILLGrenoble/visa-image-template-example#1]
Hello,

I'm trying to reproduce the example image from the repo but it seems that the `templates/visa-base/http` folder is missing, which makes the build fail.
Is this an omission or should I add it myself?

Here is the error below. I have attached a file containing the complete log: [visa-base_build.log](https://github.com/ILLGrenoble/visa-image-template-example/files/7904404/visa-base_build.log).

Thank you.

```
Building image for visa-base:
...
==> qemu: Error finding "/opt/visa-image-template/templates/visa-base/http": stat /opt/visa-image-template/templates/visa-base/http: no such file or directory
2022/01/20 10:10:07 packer-builder-qemu plugin: stdout: Image resized.
2022/01/20 10:10:07 packer-builder-qemu plugin: stderr:
==> qemu: Deleting output directory...
2022/01/20 10:10:08 [INFO] (telemetry) ending qemu
==> Wait completed after 6 seconds 525 milliseconds
Build 'qemu' errored after 6 seconds 525 milliseconds: Error finding "/opt/visa-image-template/templates/visa-base/http": stat /opt/visa-image-template/templates/visa-base/http: no such file or directory
2022/01/20 10:10:08 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2022/01/20 10:10:08 machine readable: qemu,error []string{"Error finding \"/opt/visa-image-template/templates/visa-base/http\": stat /opt/visa-image-template/templates/visa-base/http: no such file or directory"}
==> Builds finished but no artifacts were created.
2022/01/20 10:10:08 [INFO] (telemetry) Finalizing.

==> Wait completed after 6 seconds 525 milliseconds

==> Some builds didn't complete successfully and had errors:
--> qemu: Error finding "/opt/visa-image-template/templates/visa-base/http": stat /opt/visa-image-template/templates/visa-base/http: no such file or directory

==> Builds finished but no artifacts were created.
...
```

**Comment by Atlas974** [comment]
From what I understand, this could be related to the way `packme` generates the `manifest.json` files from the `manifest.yml` files.
Although the `http_directory` field is only present in `system-base/manifest.yml`, after running `packme` it is also generated in `visa-base/manifest.json` and `visa-apps/manifest.json`. Is this the expected behavior?

**Comment by stuartcaunt** [comment]
Yes, this was indeed a problem due to an updated version of packer. The changes have already been integrated into the "dev" branch and will be merged into main shortly.
